import streamlit as st
import os
from motivation_engine import get_motivation
from PIL import Image
from gtts import gTTS
import tempfile

# Page config
st.set_page_config(page_title="🧠 VibeLift: Recharge Your Mind", layout="centered")

# Custom Title
st.markdown("<h1 style='text-align: center;'>🧠 VibeLift: Recharge Your Mind</h1>", unsafe_allow_html=True)
st.markdown("#### <center>Let the AI coach lift your spirits ✨</center>", unsafe_allow_html=True)
st.write("")

# Collect user inputs
name = st.text_input("What's your name?", "Ali")

predefined_mood = st.selectbox("How are you feeling today?", ["Happy 😄", "Sad 😢", "Stressed 😖", "Excited 🤩", "Calm 😌", "Angry 😠", "Anxious 😬"])
mood_description = st.text_input("Or describe your mood in your own words", "")

time_of_day = st.selectbox("What time of day is it?", ["Morning 🌅", "Afternoon 😊", "Evening 🌇", "Night 🌙"])

tone = st.radio("Choose your preferred tone:",
                ["Inspirational 🌟", "Friendly 😊", "Tough Love ❤️", "Spiritual 🍃"])

# Use custom mood if entered
mood_input = mood_description if mood_description.strip() else predefined_mood

# Generate motivation
if st.button("❤️ Get Motivation / Regenerate"):
    message, image_url = get_motivation(name, mood_input, time_of_day, tone)
    st.session_state.message = message
    st.session_state.image_url = image_url

# Display message
if "message" in st.session_state:
    st.markdown("### 💬 Your Message:")
    st.success(st.session_state.message)

# Read Aloud button
if "message" in st.session_state and st.button("🔊 Read it Aloud"):
    tts = gTTS(text=st.session_state.message, lang='en')
    with tempfile.NamedTemporaryFile(delete=False, suffix=".mp3") as tmpfile:
        tts.save(tmpfile.name)
        st.audio(tmpfile.name, format="audio/mp3")

# Display image
if "image_url" in st.session_state:
    st.markdown("### 🖼️ Your Mood-Inspired Image:")
    st.image(st.session_state.image_url, caption="Generated by DALL·E 3")

# Personal Footer
st.markdown("---")
st.markdown("#### 👤 About the Creator")
image = Image.open("Ali Almalki.JPG")
st.image(image, width=200)
st.markdown("""
👨🏻‍💻 Built with love by Ali Almalki  
📍 Jeddah & NEOM | MSc in Data Science | AI Enthusiast  
💼 Applying for Vibe Coder @ HUMAIN  
""")
